### ISSUE TITLE
[bug] lock buttons and clean the screen

### ISSUE THREAD

**Issue by rafaell-lycan** [bruno-caldeira/simple-calc#2]
When you press more than 1 time the "0" key, you must show only one time the number.

When you did a simple math and you have the result on the screen, if you press another key/number, the display must be cleaner first.

KR

**Comment by bruno-caldeira** [comment]
- Now it doesn't matter how many times you hit "0" key, it only appears once.
- After result is shown and any key is pressed, the screen is cleared.
